shellcheck

diff --git a/ppa-cli b/ppa-cli
--- a/ppa-cli
+++ b/ppa-cli
@@ -2,7 +2,7 @@
 
 
 error(){
-    echo "ERROR: $@" >&2
+    echo "ERROR: $*" >&2
 }
 
 
